defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
  email="email@provider.com"
  storage="/acme.json"
  entryPoint = "https"

[acme.httpChallenge]
   entryPoint = "http"

[[acme.domains]]
  main = "domain.com"
  sans = ["subdomain.com"]
[api]
